  serial:
    port: /dev/ttyUSB0  # 串口号,windwos下为COMx,linux下为/dev/ttyUSBx
  lidar:
    filter_angles: [[30, 60],[120,150],[210,240],[300,330],[30,160]]  # 激光雷达过滤角度
    trust_distance_range: [3, 800]  # 激光雷达可信距离范围,单位cm
  robot:
    init_pose: [100, 250, -1.57]  # 机器人初始位置
    xy_limit: [310, 260]  # 机器人xy位置地图限制,建议与地图像素大小一致
    move_limit: 10  # 机器人每帧移动距离限制
  likelihood_field:
    levels: 2  # 似然场层数
    ratios: [0.2, 1]  # 相比占据栅格图的比例尺,可以代表每层缩小多少倍
    range: 20  # 似然场大小
    cache: True  # 是否重新计算似然场
    path: ./maps # 似然场地图路径
  map:
    path: ./maps/map1.png  # 地图路径
  test:
    save_log: False # 是否保存日志
    save_path: ./logs  # 测试保存路径
  socket:
    send_port: 23333
    recv_port: 23334