  serial: #串口相关配置，用于激光雷达的数据读取
    port: COM2  # 串口号,windwos下为COMx,linux下为/dev/ttyUSBx，对于com>10，需要使用\\\\.\\COMx（自己查必应吧）
  lidar: #激光雷达相关配置
    filter_angles: [[30, 60],[120,150],[210,240],[300,330]]  # 激光雷达过滤角度，只有不在这些角度范围内的数据才会被使用
    trust_distance_range: [3, 800]  # 激光雷达可信距离范围，大于或小于这个距离的数据舍弃，单位为厘米
  robot: #机器人相关配置
    init_pose: [30, 220, -1.57]  # 机器人初始位置，包括x坐标、y坐标和方向角（弧度制）
    xy_limit: [310, 260]  # 机器人xy位置地图限制，建议与地图像素大小一致，对于定位时可以避免机器人位置飘出场地外
    move_limit: 10  # 机器人每帧移动距离限制，与定位结合，可以避免机器人移动过快导致定位不准确
  likelihood_field: #似然场相关配置
    levels: 2  # 似然场层数
    ratios: [0.2, 1]  # 相比占据栅格图的比例尺,可以代表每层缩小多少倍
    range: 20  # 似然场大小
    lost_cost: 4.5 # 认为机器人丢失时的阈值，这个值是与点云分布在地图上的情况有关
    cache: True  # 是否使用上次缓存的似然场，如果False则会重新计算似然场，修改似然场参数后基本都需要重新计算似然场
    path: ./maps # 似然场地图路径
  map: #地图相关配置
    path: ./maps/map1.png  # 地图路径
  test: #测试相关配置
    save_log: False # 是否保存日志，True为保存，保存时占用计算算力很大。
    save_path: ./logs  # 测试保存路径
    use_log_path: logs/log_0317135854.json #仿真Location_simulation使用的日志路径
  socket:
    port: 23333  #数据与主程序交互用的端口

